ServerName                      "FrankenPHP Server"
ServerType                      standalone
DefaultServer                   on

Port                            2022
UseIPv6                         off

<IfModule mod_sftp.c>
  SFTPEngine on
  Port 2022
  SFTPLog /dev/stdout

  SFTPHostKey /etc/ssh/ssh_host_rsa_key
  SFTPHostKey /etc/ssh/ssh_host_ed25519_key

  SFTPAuthMethods password
  SFTPCompression delayed
</IfModule>

# Виртуальные пользователи
AuthUserFile /etc/proftpd/ftpasswd.users
AuthGroupFile /etc/proftpd/ftpasswd.groups

RequireValidShell off
AllowChrootSymlinks on
DefaultRoot /app ${SFTP_USER}

<Limit LOGIN>
  AllowUser ${SFTP_USER}
  DenyAll
</Limit>

SystemLog /dev/stdout